FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y python-dev python-numpy python-scipy git python-pip
RUN pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
RUN pip install six virtualenv

ENV PYTHONPATH /usr/lib/python2.7/dist-packages/:$PYTHONPATH

RUN mkdir -p /root/.ssh

COPY builder.pem /root/.ssh/id_rsa
RUN chmod 700 /root/.ssh/id_rsa

RUN git config --global url.ssh://git@github.com/.insteadOf https://github.com/

ONBUILD RUN ssh-keyscan -H github.com > /root/.ssh/known_hosts
ONBUILD COPY requirements.prod /app/src/requirements.prod
ONBUILD RUN virtualenv --system-site-packages /app/venv
# Needs to be oneliner because RUN uses it's own shell instance
ONBUILD RUN . /app/venv/bin/activate; pip install -r /app/src/requirements.prod --src /app/venv/lib/python2.7/site-packages
ONBUILD COPY . /app/src
